import webpush from 'web-push';
import { PushSubscriptionModel } from '../models/PushSubscription.js';

export interface PushPayload {
    title: string;
    body: string;
    icon?: string;
    badge?: string;
    tag?: string;
    url?: string;
    data?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// IMPORTANT: Admin and Manager are "super roles" — they receive ALL pushes.
// Any role-specific push (e.g. to 'Housekeeping') also fans out to Admin+Manager.
// This mirrors the socket room logic where Admin sees everything.
// ---------------------------------------------------------------------------
const SUPER_ROLES = ['Admin', 'Manager'];

// ---------------------------------------------------------------------------
// Lazy VAPID initialisation — reads env vars on first push attempt, not at
// module load. This prevents a missing VAPID key from crashing Express startup.
// ---------------------------------------------------------------------------
let vapidConfigured = false;

function ensureVapidConfigured(): boolean {
    if (vapidConfigured) return true;

    const publicKey = process.env.VAPID_PUBLIC_KEY;
    const privateKey = process.env.VAPID_PRIVATE_KEY;
    const subject = process.env.VAPID_SUBJECT || 'mailto:admin@smanahotels.com';

    if (!publicKey || !privateKey) {
        console.warn(
            '[Push] ⚠️  VAPID keys not configured — OS push notifications are DISABLED.\n' +
            '         Set VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, and VAPID_SUBJECT in .env to enable them.'
        );
        return false;
    }

    try {
        webpush.setVapidDetails(subject, publicKey, privateKey);
        vapidConfigured = true;
        console.log('[Push] VAPID keys loaded ✓');
        return true;
    } catch (err) {
        console.error('[Push] Invalid VAPID keys — check that they were generated by web-push:', err);
        return false;
    }
}

// ---------------------------------------------------------------------------
// sendPushToRole
//
// Sends to the given role AND always fans out to Admin + Manager (super roles).
// This ensures admins always see every notification regardless of which
// role-specific createNotification() was called.
// Duplicate subscriptions (e.g. an Admin who is in both Admin and the role)
// are collapsed by the `tag` field on the notification.
// ---------------------------------------------------------------------------
export async function sendPushToRole(role: string, payload: PushPayload): Promise<void> {
    if (!ensureVapidConfigured()) return;

    // Always include super roles so Admins/Managers receive every event
    const targetRoles = [...new Set([role, ...SUPER_ROLES])];
    const subscriptions = await PushSubscriptionModel.find({ role: { $in: targetRoles } });
    await _sendToSubscriptions(subscriptions, payload);
}

// sendPushToRoles — convenience for sending to a specific list of roles
export async function sendPushToRoles(roles: string[], payload: PushPayload): Promise<void> {
    if (!ensureVapidConfigured()) return;
    const targetRoles = [...new Set([...roles, ...SUPER_ROLES])];
    const subscriptions = await PushSubscriptionModel.find({ role: { $in: targetRoles } });
    await _sendToSubscriptions(subscriptions, payload);
}

// sendPushToUser — user-specific push (e.g. guest gets status update)
export async function sendPushToUser(userId: string, payload: PushPayload): Promise<void> {
    if (!ensureVapidConfigured()) return;
    const subscriptions = await PushSubscriptionModel.find({ userId });
    await _sendToSubscriptions(subscriptions, payload);
}

// ---------------------------------------------------------------------------
// Internal
// ---------------------------------------------------------------------------
async function _sendToSubscriptions(
    subscriptions: Array<{ endpoint: string; keys: { p256dh: string; auth: string }; _id: any }>,
    payload: PushPayload
): Promise<void> {
    if (subscriptions.length === 0) {
        console.log('[Push] No subscriptions found for this role — skipping push');
        return;
    }

    const pushPayload = JSON.stringify({
        title: payload.title,
        body: payload.body,
        icon: payload.icon || '/icon-192.png',
        badge: payload.badge || '/icon-96.png',
        tag: payload.tag,
        data: {
            url: payload.url || '/dashboard',
            ...(payload.data || {}),
        },
    });

    const results = await Promise.allSettled(
        subscriptions.map(async (sub) => {
            try {
                await webpush.sendNotification(
                    { endpoint: sub.endpoint, keys: { p256dh: sub.keys.p256dh, auth: sub.keys.auth } },
                    pushPayload
                );
            } catch (err: any) {
                if (err.statusCode === 410 || err.statusCode === 404) {
                    // Subscription expired — clean up automatically
                    console.log(`[Push] Removing expired subscription: ${sub.endpoint.slice(0, 60)}…`);
                    await PushSubscriptionModel.findByIdAndDelete(sub._id);
                } else {
                    console.error(`[Push] Failed to send to endpoint:`, err.message);
                }
            }
        })
    );

    const sent = results.filter((r) => r.status === 'fulfilled').length;
    console.log(`[Push] Delivered ${sent}/${subscriptions.length} notifications for "${payload.title}"`);
}
